USE online_store;

INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Morra Origini Brasilia Santos Strictly Soft Fine Cup, cafea proaspat prajita 1kg', 'Morra Origini Brasilia Santos SSFC\n\nBoabele de cafea din regiunea Santos, Brasil, oferă o varietate plăcută de note de gust, perfectă pentru tipuri de preparare de la cafea de filtru la espresso. Dacă sunteți în căutarea unei cafele cu conținut scăzut în aciditate, Brasil Santos este perfectă. Veți savura o cafea dulce, fină, cu aciditate medie, note de nuci și aromă de ciocolată.\n\nBoabele verzi de cafea sunt prăjite de către echipa Morra Origini pentru dumneavoastră astfel încât aromele originale să fie păstrate și evidențiate pentru a oferi experiența unei cafele de specialitate proaspăt prăjită de cea mai bună calitate.', 'https://s13emagst.akamaized.net/products/39324/39323549/images/res_4d755ac84bf2febb201e6d236dce45c9.jpg', 'Morra', 78.39);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Lavazza Super Crema cafea boabe 1kg', 'Cafeaua Lavazza Super Crema Espresso este un amestec de cafea cu aromă de alune de padure si zahar brun, cu o cremă catifelată și consistentă, împreună creând un espresso ușor și cremos.  Această cafea este recomandată pentru baruri și restaurante.\n\nCafeaua boabe Lavazza Super Crema face parte din colecția Lavazza Classics. Sortimentele de cafea din aceasta gamă sunt cafele pline de eleganță și armonie. Astfel, aromele și gustul sunt perfect echilibrate, caracteristici specifice cafelelor clasice care reprezintă excelența tradiției a espresso-ului Lavazza.\n\nContinut: 60% Arabica- 40% Robusta\n\nDepozitarea trebuie făcută în încăperi curate, uscate și fără mirosuri străine.', 'https://s13emagst.akamaized.net/products/20993/20992375/images/res_72eef18034247db21703e3694db15b43.jpg?width=450&height=450&hash=55478848B3536E254122612A432410C4', 'Lavazza', 58.30);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Pellini Top 100% Arabica cafea boabe 1kg', 'Pellini Top 100% Arabica este cafeaua care te va cuceri cu  aroma consistenta cu un caracter puternic și bogat. Este o cafea boabe perfect prajita cu un gust puternic si o aroma desavarsita ce nu te lasa indiferent. Metoda de prăjire medie și lentă îi conferă acestui amestec un gust armonios și persistent.\n\nDepozitarea trebuie făcută în încăperi curate, uscate și fără mirosuri străine.','https://asterpremium.ro/wp-content/uploads/2021/03/Pellini-Top-1kg-e1616760686474.jpg','Pellini', 50.70);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Morra Origini Brasilia Santos Strictly Soft Fine Cup, cafea proaspat prajita, macinata, 250 g', 'Morra Origini Brasilia Santos SSFC-cafea macinata din boabe de cafea proaspat prajite.\n\nBoabele de cafea din regiunea Santos, Brasil, oferă o varietate plăcută de note de gust, perfectă pentru tipuri de preparare de la cafea de filtru la espresso. Dacă sunteți în căutarea unei cafele cu conținut scăzut în aciditate, Brasil Santos este perfectă. Veți savura o cafea dulce, fină, cu aciditate medie, note de nuci și aromă de ciocolată.\n\nBoabele verzi de cafea sunt prăjite de către echipa Morra Origini pentru dumneavoastră astfel încât aromele originale să fie păstrate și evidențiate pentru a oferi experiența unei cafele de specialitate proaspăt prăjită de cea mai bună calitate.', 'https://s13emagst.akamaized.net/products/39324/39323549/images/res_4d755ac84bf2febb201e6d236dce45c9.jpg', 'Morra', 29.80);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Lavazza Qualita Oro Mountain Grown, CUTIE, cafea macinata, 250g','Lavazza Qualita Oro Mountain Grown - un amestec unic de cafea din America Centrala, America de Sud si Etiopia, un amestec de cafea 100% Arabica, fructat și aromat cu un caracter semnificativ. Este dedicat adevăraților cunoscători ai specialităților italiene de cafea.\n\nIntensitate :7/10\n\nDepozitarea trebuie făcută în încăperi curate, uscate și fără mirosuri străine.', 'https://s13emagst.akamaized.net/products/30054/30053907/images/res_cf48c7f5911a5a528755b7aee4f1912f.jpg', 'Lavazza', 25.10);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Eilles Tee Assam Special Teebeutel - 25 plicuri', 'Eilles Tee Teebeutel Assam Special  , ceai negru– Un ceai cu o aroma puternica provenit de pe plantatiile din zona Assam (nordul Indiei).\n\nCeaiul este ambalat în pliculețe de hârtie.\n\nEste suficient să turnați apă fierbinte într-un pahar sau cană cu o capacitate de 200-300 ml și să infuzati pentru 3-4 minute plicul de ceai.\n\nCutia contine 25 plicuri x 1.5g.\n\nDepozitarea trebuie făcută în încăperi curate, uscate și fără mirosuri străine la o temperatură maximă de 18°C.', 'https://cdn.kfea.ro/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/i/eilles_tee_assam_special.jpg', 'Eilles', 13.90);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Ceai GardenFresh Peppermint Tea 25 plicuri', 'Ceai GardenFresh Peppermint Tea 25 plicuri\n\nCeai  de mentă (mentă);\n\n\nInfuzie: 1-3 minute\n\nCeaiul este ambalat în pliculețe de hârtie.\n\nContinut:  25 plicuri  * 1.5 g\nDepozitarea trebuie făcută în încăperi curate, uscate și fără mirosuri străine.', 'https://cafeo.ro/2385/gardenfresh-peppermint-tea-25-plicuri.jpg', 'GardenFresh', 17.29);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Espressor automat cu rasnita incorporata DIVA DE LUXE', 'Espressor automat cu rasnita inox incorporata Diva De Luxe, Display LED, Cafea boabe, 1.1 l, 1470 W, 19 Bar, Inox.\n\n \n\nDiva Deluxe este aparatul automat de cafea cu rasnita incorporata, display LED si pompa cu 19 bar presiune, care iti prepara, din boabe proaspat macinate, printr-o simpla atingere One Touch, un espresso perfect italian sau asa cum iti place!  Combinatia perfecta a materialelor de inalta calitate -metal si inox, design-ul  futurist si dimensiunea SLIM de doar 18 cm latime, clasifica superautomatul Diva Deluxe de la Studio Casa in zona de produs de exceptie cu performante ridicate,usor de integrat in orice ambient! Tehnologia din interior asigura aceeasi calitate a cafelei espresso ca cea pregatita la un autentic bar italian. Daca iubesti cafeaua meriti ce este mai bun; Diva Deluxe este companioana diminetilor tale si a momentelor de rasfat!', 'https://cdni.dwyn.ro/images/products/img_202106242018/162302/full/philips-espressor-automat-philips-lattego-seria-5400-ep5444-70-1-8l-1500w-15-bar-gri-argintiu-270037.webp', 'DIVA DE LUXE', 1279.90);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Espressor Francis Francis X7.1 Illy Iperespresso', 'Espressorul Francis Francis X7.1 vă prezintă un design modern si atragator și o tehnologie inovativa care ofera utilizatorului o cafea perfecta.\n\nNoul espressor X7.1 functioneaza doar cu capsulele Iperespresso. Inserati o capsula si datorita sistemului simplu de folosinta, veti obtine un espresso illy direct in ceasca, fara a avea contact cu espressorul, ceea ce se traduce printr-o mentenanta redusa. O atingere simpla pentru o performanta total noua. X7, ultima inovatie a liniei FrancisFrancis! este facut din plastic si metal.\n\nSISTEMUL IPERESPRESSO, este un sistem inchis ce foloseste capsulele illy. Un sistem inovator pentru capsule, creat de catre inventatorul espresso-ului de astazi. Preinfuzia și emulsia garanteaza un produs de calitate superioara: cremos, cu mai multa aroma si la temperatura potrivita. Acest sistem se bazeaza pe folosirea capsulelor illy, capsule ce au o camera de extractie inteligenta care imbunatateste consistenta si gustul cafelei in interiorul ei.\n\nCafeaua curge direct in ceasca, nu exista contact direct cu aparatul, caracteristicile acesteia nefiind in nici un fel influentate.', 'https://p1.akcdn.net/full/116301853.francis-francis-illy-x7-1-iper.jpg', 'Illy', 858.00);
INSERT INTO `online_store`.`products` (`title`, `description`, `image`, `producer`, `price`) VALUES ('Morra Origini Yemen Anis, cafea boabe origini, proaspat prajita, 250g',  'Yemen Anis-Editie limitata!\n\nRegiunea Anis a devenit o nouă sursă importantă în cultivarea cafelei yemenite în ultimii ani.\n\nAnis oferă cultivatorilor săi de cafea producții ample, având teren fertil, în special în comparație cu sursele tradiționale clasice din Yemen.\n\nPomii de cafea Anis cresc în zona văilor, cuibăriți între munți, precum și pe terasele montane înalte, irigate. Regiunea Anis este o sursă în ascensiune în domeniul cafelei yemenite, cu un mare potential de producție care atrage în mod justificat atenția din ce în ce mai mare din partea lumii cafelei.\n\nCele mai proeminente caracteristici ale profilului de gust ale acestei regiuni sunt notele de ciocolată, fructe uscate, fagure de miere, migdale, note fructate și dezvoltă o aciditate placută.\n\nSortimentul pe care il propunem pentru dumneavoastră vă va incita cu note complexe de miere, lămâiță, citrice și note florale. Veți descoperi o cafea delicată, de intensitate medie, care surprinde și atunci când este băută rece.\n\nBoabele verzi de cafea sunt prăjite de către echipa Morra Origini pentru dumneavoastră astfel încât aromele originale să fie păstrate și evidențiate pentru a oferi experiența unei cafele de specialitate proaspăt prăjită de cea mai bună calitate.', 'https://cdn.shopify.com/s/files/1/0614/5143/6275/products/morra-espresso-1kg_533x.png?v=1650539970', 'Morra ', 61.60);

INSERT INTO `users` (`last_name`, `first_name`, `username`, `email`,`password`,`address`,`phone_number`, `role`, `enabled`)
VALUES
    ('Angel', 'Stanciu', 'Angel', 'admin@gmail.com','$2a$12$R5KCFc1VxAsT9J5JJckCjeBms460FX25/y.b8lZ0tEr27wzJuJUYW','Romania, Bucuresti, Strada Gabroveni, 030089','+40721058124', 'ROLE_ADMIN', 1),
    ('Adina','Gheorghe', 'Adina', 'user@gmail.com','$2a$12$W.xkh6ve8TuQWVzh2Re67u5stJ4mD9lz1gdMO2o3iabb7Pvp6b3aW','Romania, Voluntari, Bulevardul Pipera 1, 077190','+40212006464', 'ROLE_USER', 1);

INSERT INTO `online_store`.`orders` (`total`, `date`, `user_id`) VALUES ('207.98', '2022-01-15', '1');
INSERT INTO `online_store`.`orders` (`total`, `date`, `user_id`) VALUES ('171.48', '2022-02-25', '2');

INSERT INTO `online_store`.`order_details` (`quantity`, `unit_price`, `product_id`, `order_id`) VALUES ('1', '78.39', '1', '1');
INSERT INTO `online_store`.`order_details` (`quantity`, `unit_price`, `product_id`, `order_id`) VALUES ('1', '25.1', '5', '1');
INSERT INTO `online_store`.`order_details` (`quantity`, `unit_price`, `product_id`, `order_id`) VALUES ('2', '17.29', '7', '1');
INSERT INTO `online_store`.`order_details` (`quantity`, `unit_price`, `product_id`, `order_id`) VALUES ('1', '61.6', '10', '2');
INSERT INTO `online_store`.`order_details` (`quantity`, `unit_price`, `product_id`, `order_id`) VALUES ('2', '50.70', '3', '2');
INSERT INTO `online_store`.`order_details` (`quantity`, `unit_price`, `product_id`, `order_id`) VALUES ('1', '78.39', '1', '2');

INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('2', '1', '1');
INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('2', '1', '3');
INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('1', '1', '2');
INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('1', '1', '10');
INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('2', '2', '7');
INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('2', '2', '8');
INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('6', '2', '5');
INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('2', '2', '2');
INSERT INTO `online_store`.`cart_items` (`quantity`, `user_id`, `product_id`) VALUES ('1', '2', '1');

